### ISSUE TITLE
Floor raycasting

### ISSUE THREAD

**Issue by salvadorc17** [Owlzy/OwlRaycastEngine#1]
Youre able to do floors raycasting with tihs method, seems very interesting implementation

**Comment by Owlzy** [comment]
I never got around to implementing this feature, however it would be fairly straightforward to add.

**Comment by harbdog** [comment]
FYI was able to add raycasted floors by following that lodev tutorial, though in my Golang conversion of this project that has since been carried forward to include quite a bit more:

https://github.com/harbdog/raycaster-go
